# Generated by Django 3.1.4 on 2020-12-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
